# Generated by Django 2.2.16 on 2022-04-15 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220415_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message=('Enter a valid username. This value may contain only ', 'letters, digits and @/./+/-/_ characters.'), regex='^[\\w.@+-]+$')]),
        ),
    ]
