# Generated by Django 2.2.16 on 2022-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'User'), (2, 'Moderator'), (3, 'Admin')], default=1, null=True),
        ),
    ]
