# Generated by Django 2.2.16 on 2022-04-18 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220418_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='This value may contain only letters,\n                digits and @/./+/-/_ characters.', regex='^[\\w.@+-]+$'), django.core.validators.RegexValidator(inverse_match=True, message='Username Me registration not allowed.', regex='^\\b(m|M)e\\b')]),
        ),
    ]
