# Generated by Django 2.2.16 on 2022-04-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220418_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'User'), (2, 'Moderator'), (3, 'Admin')], default=1, max_length=100, null=True),
        ),
    ]
