# Generated by Django 2.2.16 on 2022-04-19 15:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220418_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.models.validate_username]),
        ),
    ]
