# Generated by Django 2.2.16 on 2022-04-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220417_1154'),
        ('reviews', '0002_auto_20220417_1357'),
    ]

    operations = [
    ]
