# Generated by Django 2.2.16 on 2022-04-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_merge_20220417_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.ForeignKey(choices=[(1, 'один'), (2, 'два'), (3, 'три'), (4, 'четыре'), (5, 'пять'), (6, 'шесть'), (7, 'семь'), (8, 'восемь'), (9, 'девять'), (10, 'десять')], default=10, help_text='Оцените произведение', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reviews', to='reviews.Rating'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.Title'),
            preserve_default=False,
        ),
    ]
