# Generated by Django 2.2.16 on 2022-04-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220420_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.CharField(help_text='Оцените произведение', max_length=10),
        ),
    ]
